[general]
shuffle_caption = true
caption_extension = ".txt"
keep_tokens = 2

[[datasets]]
resolution = [1024, 1024]
batch_size = 1
enable_bucket = true
bucket_no_upscale = true
bucket_reso_steps = 64
min_bucket_reso = 256
max_bucket_reso = 1536

  [[datasets.subsets]]
  image_dir = "C:/Users/dodo/Documents/Codex/ACG_AI_picture/data/train/senren_banka_asatake_yoshino"
  num_repeats = 8
